# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.

{{- if or .Values.backup.enable .Values.backup.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "timescaledb.fullname" . }}-backup
  labels:
<<<<<<< HEAD
    app: {{ template "timescaledb.fullname" . }}
    chart: {{ template "timescaledb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cluster-name: {{ template "clusterName" . }}
||||||| parent of b8c78e8 (chart/timescaledb-single: unify labels across resources)
{{ include "timescaledb-helm.labels" . | indent 4}}
    app.kubernetes.io/component: backup
=======
    {{ include "timescaledb-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
>>>>>>> b8c78e8 (chart/timescaledb-single: unify labels across resources)
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: {{ template "timescaledb.fullname" . }}
    role: master
    cluster-name: {{ template "clusterName" . }}
...
{{- range .Values.backup.jobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "timescaledb.fullname" $ }}-{{ .name }}
  labels:
    app: {{ template "timescaledb.fullname" $ }}
    chart: {{ template "timescaledb.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    backup-type: {{ .type }}
<<<<<<< HEAD
<<<<<<< HEAD
    cluster-name: {{ template "clusterName" $ }}
||||||| parent of b8c78e8 (chart/timescaledb-single: unify labels across resources)
{{ include "timescaledb-helm.labels" $ | indent 4}}
    app.kubernetes.io/component: backup
=======
    {{ include "timescaledb-helm.labels" . | nindent 4 }}
||||||| parent of b931098 (Fix scope in range for labels templating)
    {{ include "timescaledb-helm.labels" . | nindent 4 }}
=======
    {{ include "timescaledb-helm.labels" $ | nindent 4 }}
>>>>>>> b931098 (Fix scope in range for labels templating)
    app.kubernetes.io/component: backup
>>>>>>> b8c78e8 (chart/timescaledb-single: unify labels across resources)
spec:
  schedule: {{ quote .schedule }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: {{ template "timescaledb.fullname" $ }}
        backup-type: {{ .type }}
        cluster-name: {{ template "clusterName" $ }}
    spec:
      activeDeadlineSeconds: {{.activeDeadlineSeconds}}
      template:
        metadata:
          labels:
            app: {{ template "timescaledb.fullname" $ }}
            backup-type: {{ .type }}
            cluster-name: {{ template "clusterName" $ }}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ template "timescaledb.serviceAccountName" $ }}
          containers:
            - name: {{ template "timescaledb.fullname" $ }}-{{ .type }}
              image: dtzar/helm-kubectl
              command: ["/bin/bash"]
              args:
              - -c
              - 'kubectl exec -i $(kubectl -n {{ $.Release.Namespace }} get pod -l role=master -oName) -n {{ $.Release.Namespace }} -c timescaledb -- pgbackrest backup --type={{ quote .type }} --log-level-console=detail'
...
{{- end }}
{{- if ne .Values.secrets.slack.token "" }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "timescaledb.fullname" $ }}-pgbackrest-info
  labels:
    app: {{ template "timescaledb.fullname" $ }}
    chart: {{ template "timescaledb.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    cluster-name: {{ template "clusterName" $ }}
spec:
  schedule: "12 14 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: {{ template "timescaledb.fullname" $ }}
        cluster-name: {{ template "clusterName" $ }}
    spec:
      activeDeadlineSeconds: 60
      template:
        metadata:
          labels:
            app: {{ template "timescaledb.fullname" $ }}
            cluster-name: {{ template "clusterName" $ }}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ template "timescaledb.serviceAccountName" $ }}
          containers:
            - name: {{ template "timescaledb.fullname" $ }}-pgbackrest-info
              image: dtzar/helm-kubectl
              command: ["/bin/bash"]
              args:
              - -c
              - 'curl -s -H "multipart/form-data" -H "application/x-www-form-urlencoded" -d token="{{ .Values.secrets.slack.token }}" -d channels={{ .Values.secrets.slack.channel }} -d initial_comment="{{ upper $.Release.Name }} - ({{ .Values.kubernetesClusterName}}) PGBackrest Info" -d filetype="text" -d title="PGBackrest Info" -d content="$(kubectl exec -it $(kubectl -n {{ $.Release.Namespace }} get pod -l role=master -oName) -n {{ $.Release.Namespace }} -c timescaledb -- pgbackrest info)" https://slack.com/api/files.upload'
...
{{- end }}
{{ end }}