name: Deprecate multinode chart
on:
  push:
    paths:
    - 'charts/timescaledb-multinode/**'
  pull_request:
    paths:
    - 'charts/timescaledb-multinode/**'

jobs:
  do-not-commit:
    runs-on: ubuntu-latest
    name: timescaledb-multinode chart is deprecated
    steps:
    - run: exit 1
