apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "parca-server.fullname" . }}-config
  namespace: {{ template "parca-server.namespace" . }}
  labels:
{{- include "parca-server-helm.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete
    "helm.sh/hook-weight": "0"
data:
  parca.yaml: |
{{- toYaml .Values.config | nindent 4 }}
