apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "parca-server.fullname" . }}
  namespace: {{ template "parca-server.namespace" . }}
  labels:
{{- include "parca-server-helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "parca-server.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "parca-server.serviceAccountName" . }}
