{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "parca-server.serviceAccountName" . }}
  namespace: {{ template "parca-server.namespace" . }}
  labels:
{{- include "parca-server-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
{{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
